security:
    password_hashers:
        App\Entity\Users:
            algorithm: auto

    providers:
        users_in_db:
            entity:
                class: App\Entity\Users
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # API firewall for JWT
        api:
            pattern: ^/api
            stateless: true
            provider: users_in_db
            jwt: ~


        main:
            lazy: true
            provider: users_in_db
            entry_point: App\Security\AdminAuthenticator

            # Don't use form_login here; the custom authenticator handles it
            custom_authenticator: App\Security\AdminAuthenticator

            logout:
                path: app_logout
                target: app_login
                invalidate_session: true
            
            form_login:
                login_path: login
                check_path: login

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /

    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_HR, ROLE_FINANCE, ROLE_SALES, ROLE_PROCUREMENT, ROLE_PRODUCTION, ROLE_PROJECT_MANAGER, ROLE_STAFF, ROLE_GUEST]
        ROLE_ADMIN: []
        ROLE_HR: []
        ROLE_FINANCE: []
        ROLE_SALES: []
        ROLE_PROCUREMENT: []
        ROLE_PRODUCTION: []
        ROLE_PROJECT_MANAGER: []
        ROLE_STAFF: []
        ROLE_GUEST: []


    access_control:
        - { path: ^/admin/hr, roles: ROLE_HR }
        - { path: ^/admin/finance, roles: ROLE_FINANCE }
        - { path: ^/admin/sales, roles: ROLE_SALES }
        - { path: ^/admin/procurement, roles: ROLE_PROCUREMENT }
        - { path: ^/admin/production, roles: ROLE_PRODUCTION }
        - { path: ^/admin/projects, roles: ROLE_PROJECT_MANAGER }
        - { path: ^/admin/staff, roles: ROLE_STAFF }



    # API access
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }