parameters:
    app.available_roles:
        - ROLE_SUPER_ADMIN
        - ROLE_ADMIN
        - ROLE_HR
        - ROLE_FINANCE
        - ROLE_SALES
        - ROLE_PROCUREMENT
        - ROLE_PRODUCTION
        - ROLE_PROJECT_MANAGER
        - ROLE_STAFF
        - ROLE_GUEST

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true

    # makes classes in src/ available as services
    App\:
        resource: '../src/'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # HR Dashboard Service
    App\Service\HrDashboardService:
        arguments:
            $usersRepository: '@App\Repository\UsersRepository'
            $departmentRepository: '@App\Repository\DepartmentRepository'
            $leaveRequestRepository: '@App\Repository\LeaveRequestRepository'
            $attendanceRepository: '@App\Repository\AttendanceRepository'
            $payRollRepository: '@App\Repository\PayRollRepository'
            $entityManager: '@doctrine.orm.entity_manager'

    # Commands
    App\Command\:
        resource: '../src/Command'

    # Twig extensions
    App\Twig\AppExtension:
        tags: [twig.extension]
